### ISSUE TITLE
App link intent appear when clicking on Terms and Policy Section

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-attendee-android#2292]
**Describe the bug**
App deep linking appear when clicking on Terms and Policy Section

**Screenshots**
<img src="https://i.ibb.co/6BvYksz/ezgif-1-183909d052bc.gif" alt="ezgif-1-183909d052bc" border="0">

**Would you like to work on the issue?**
Open to all

**Comment by rajput2122** [comment]
hello sir, can you please elaborate more about app deep linking. I am glad to contribute

**Comment by anhanh11001** [comment]
In the Screenshot, the part of "Use a different app" Eventyay Attendee should not show up. About Deep Linking, just google to read more about it and ask if you have any questions

**Comment by rajput2122** [comment]
Thank you, sir, i will start fixing it.i have downloaded the app from play store and saw the issue

**Comment by liveHarshit** [comment]
@rajput2122 Any updates?

**Comment by rajput2122** [comment]
I have done this.is this issue is closed sir?

**Comment by ShridharGoel** [comment]
@rajput2122 No, you can send a PR.

**Comment by rajput2122** [comment]
actually, sir while fixing another issue in this app while debugging for that issue when I checked by clicking on terms and policy this app didn't open in-app deep linking and the link opened in the browser. While fixing that issue I changed some link in setting.xml file, I think it reflects in this issue also and I have made pr for that issue which was merged yesterday.
[2019_08_28_14_21_12.zip](https://github.com/fossasia/open-event-attendee-android/files/3550060/2019_08_28_14_21_12.zip)

 Can I make new PR?

**Comment by rajput2122** [comment]
PR for deep linking issue please review this.

**Comment by rajput2122** [comment]
I have fixed this issue yesterday removed suggestion form from settings and README #2315
after fixing this issue I checked deep linking issues this issue also got solved. Can you please see #2315 and close this issue, sir?

**Comment by rajput2122** [comment]
Sir i am not able to modify my PR. Can you please help me?

**Comment by rajput2122** [comment]
Actually sir this issue is no longer exist. Please confirm

**Comment by liveHarshit** [comment]
> Actually sir this issue is no longer exist. Please confirm

Please test with replacing debug URLs with release URLs in app level gradle file. The issue is still there.

**Comment by rajput2122** [comment]
Okk sir

**Comment by rahulpansari** [comment]
Sir please correct me if i am wrong as i saw the link need to be directly open to the app iteself?
If that is the case then
It can be solved using Android App link.
I would like to work on this issue.

**Comment by liveHarshit** [comment]
@rahulpansari, Please ask @rajput2122 to work on this issue. We do not assign same issue to multiple contributors.

**Comment by liveHarshit** [comment]
> Sir please correct me if i am wrong as i saw the link need to be directly open to the app iteself?
> If that is the case then
> It can be solved using Android App link.
> I would like to work on this issue.

His Pr is closed. Go ahead just check the type of URL. If it contains `/e/` path segment the take intent otherwise not.

**Comment by rajput2122** [comment]
@liveHarshit sir i have checked by changing debugbaseurl to releasebaseurl in app level gradle file.There is no such issue .can you please see this am i right in changing the release url to debug url 
![image](https://user-images.githubusercontent.com/43101744/64278599-c334a100-cf6a-11e9-948c-333a3e539a0c.png)

**Comment by liveHarshit** [comment]
> @liveHarshit sir i have checked by changing debugbaseurl to releasebaseurl in app level gradle file.There is no such issue .can you please see this am i right in changing the release url to debug url
> ![image](https://user-images.githubusercontent.com/43101744/64278599-c334a100-cf6a-11e9-948c-333a3e539a0c.png)

Change the frontend host too. This field is especially for App link intents.

**Comment by rajput2122** [comment]
okk sir

**Comment by rajput2122** [comment]
Sir can i remove some code from menifest for debugging?

**Comment by anhanh11001** [comment]
> Sir can i remove some code from menifest for debugging?

Yes, but don't commit that, just push the necessary changes when making a PR

**Comment by rajput2122** [comment]
> > Sir can i remove some code from menifest for debugging?
> 
> Yes, but don't commit that, just push the necessary changes when making a PR

but this issue get solved while testing by this removal

**Comment by anhanh11001** [comment]
Then it is fine, just do it, send the PR and the solution will be reviewed

**Comment by rahulpansari** [comment]
Yes its working fine after app linking is done

**Comment by liveHarshit** [comment]
> Yes its working fine after app linking is done

What app linking is done??

**Comment by rob729** [comment]
@anhanh11001 @liveHarshit Can I work on this issue?

**Comment by rajput2122** [comment]
@rob729 i am working on it

**Comment by liveHarshit** [comment]
@rob729 You can work on other issues

**Comment by rob729** [comment]
> @rob729 i am working on it

Ok

**Comment by rob729** [comment]
@rajput2122 are you still working on this issue?

**Comment by iamareebjamal** [comment]
Go ahead @rob729

**Comment by rob729** [comment]
@iamareebjamal @anhanh11001 I am not able to reproduce the issue in the app.
I think it is already solved.

<a href="https://imgflip.com/gif/3akaqt"><img src="https://i.imgflip.com/3akaqt.gif" title="made at imgflip.com"/></a>

**Comment by liveHarshit** [comment]
> > Actually sir this issue is no longer exist. Please confirm
> 
> Please test with replacing debug URLs with release URLs in app level gradle file. The issue is still there.

@rob729

**Comment by rob729** [comment]
Ok

**Comment by liveHarshit** [comment]
> Ok

Always read previous comments before taking up any issue for good practices :+1:
